AllCops:
  TargetRubyVersion: 2.3

  Documentation:
    Enabled: false

  Lint/AmbiguousBlockAssociation:
    Enabled: false

  Metrics/AbcSize:
    Max: 30

  Metrics/BlockLength:
    Enabled: false

  Metrics/LineLength:
    Max: 120

  Metrics/MethodLength:
    Max: 30

  Metrics/ModuleLength:
    Max: 200

  Style/ClassAndModuleChildren:
    EnforcedStyle: nested

  Style/FormatStringToken:
    EnforcedStyle: template

  Style/FrozenStringLiteralComment:
    Enabled: false

  Style/GuardClause:
    Enabled: false

  Style/IfUnlessModifier:
    Enabled: false
